# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: el # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/
theme: jekyll-theme-simple-texture
remote_theme: yizeng/jekyll-theme-simple-texture

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: #www.zimosi.gr This can cause the failure of image loading.
baseurl: # the subpath of your site, e.g. /blog
title: Zimosi.gr
description: "Ας μιλήσουμε για ζυμώσεις!"
keywords: 'ζυμωση,fermentation,homebrew'
author:
  name: Δρακόντης Παναγιώτης
  email: drakontis.panagiotis@gmail.com
  social_links:
    - name: facebook
      url: https://www.facebook.com/drakontispanagiotis
    - name: github
      url: https://github.com/drakontis/fermentations
    - name: linkedin
      url: https://www.linkedin.com/in/drakontispanagiotis
blog:
#  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
#  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License.
  footer_content: 2018 zimosi.gr

disqus:
  shortname: zimosi-gr
  public_key: gfxAsXBvRsbrmckMbNIxdoCpilc39gAUugJzFQxGGnZ9QwqdNegkYUEP0ZHS9dDS
google_analytics: # e.g. 'UA-42456515-5'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5 

paths:
  home: /
  blog: /
  categories: /blog/categories/
  tags: /blog/tags/
